lib/matplotlib/mpl-data/fonts/ /usr/share/matplotlib/mpl-data/
lib/matplotlib/mpl-data/images/ /usr/share/matplotlib/mpl-data/
matplotlibrc.template /usr/share/matplotlib/matplotlib.conf
lib/matplotlib/mpl-data/matplotlibrc /etc/
lib/matplotlib/mpl-data/matplotlibrc /usr/share/matplotlib/mpl-data/
lib/matplotlib/mpl-data/sample_data/ /usr/share/matplotlib/
lib/matplotlib/mpl-data/stylelib/ /usr/share/matplotlib/mpl-data/
